#!/bin/sh

# ros-dpkg/build-all

set -euvx

this="$(realpath "$0")"
readonly this="${this}"
here="$(dirname "${this}")"
readonly here="${here}"
whatami="$(basename "${this}")"
readonly whatami="${whatami}"
tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"
readonly tmpdir="${tmpdir}"

log() { echo "${whatami}[$$]: $*" >&2; }
error() { log "ERROR: $*"; }
warning() { log "WARNING: $*"; }
info() { log "INFO: $*"; }

die() {
    error "$*"
    usage >&2
    exit 1
}

cleanup() {
    status="$?"
    if command -v docker >/dev/null 2>&1; then
        docker system prune --force --filter until=6h >&2 || true
    fi
    rm -rf "${tmpdir}"
    return "${status}"
}

usage() {
    cat <<EOF

Usage: $0 [OPTION]...
Build all the things.

EOF
}

################################################################################

trap cleanup EXIT
chmod 1777 "${tmpdir}"
export TMPDIR="${tmpdir}"
export LC_ALL=C

git -C "${here}" branch -a \
    | sed -nr 's|^  remotes/[^/]+/([[:graph:]]+)$|\1|gp' \
    | sed 's/master/latest/' \
    | sort -u \
    | while read -r brunch; do
        export IMAGE_NAME="registry.gitlab.com/realtime-robotics/ros-dpkg:${brunch}"
        "${here}/hooks/build"
    done

exit "$?"
