#!/bin/sh

# ros-debbah/configure-rosdep

set -eu

readonly this="$(readlink -f "$0")"
readonly here="$(dirname "${this}")"
readonly whatami="$(basename "${here}").$(basename "${this}")"
readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"

log() { echo "${whatami}[$$]: $@" >&2; }
error() { log "ERROR: $@"; }
warning() { log "WARNING: $@"; }
info() { log "INFO: $@"; }

die() {
    error "$@"
    usage >&2
    exit 1
}

cleanup() {
    status="$?"
    rm -rf "${tmpdir}"
    return "${status}"
}

usage() {
    cat <<EOF
Usage: $(basename ${this})
Configure rosdistro to use additional repositories.

Examples:

    \$ $(basename ${this})
EOF
}

################################################################################

trap cleanup EXIT
export TMPDIR="${tmpdir}"
export LC_ALL=C

if ! [ 0 -eq "$(id -u)" ]; then
    sudo "${this}"
    exit "$?"
fi

while getopts ":h" opt; do
    case "${opt}" in
        h)
            usage
            exit 0
            ;;
        :) die "missing argument: -${OPTARG}" ;;
        \?) die "bad option: -${OPTARG}" ;;
    esac
done
shift "$((${OPTIND} - 1))"

cat >/srv/realsense.yaml <<'EOF'
intel-realsense-dfu:
  ubuntu: [intel-realsense-dfu]
librealsense2:
  ubuntu: [librealsense2]
librealsense2-dbg:
  ubuntu: [librealsense2-dbg]
librealsense2-dev:
  ubuntu: [librealsense2-dev]
librealsense2-dkms:
  ubuntu: [librealsense2-dkms]
librealsense2-udev-rules:
  ubuntu: [librealsense2-udev-rules]
librealsense2-utils:
  ubuntu: [librealsense2-utils]
librscalibrationapi:
  ubuntu: [librscalibrationapi]
librscalibrationtool:
  ubuntu: [librscalibrationtool]
realsense-sdk:
  ubuntu: [realsense-sdk]
realsense-sdk-dbg:
  ubuntu: [realsense-sdk-dbg]
realsense-sdk-dev:
  ubuntu: [realsense-sdk-dev]
realsense-sdk-udev-rules:
  ubuntu: [realsense-sdk-udev-rules]
realsense-sdk-utils:
  ubuntu: [realsense-sdk-utils]
rs-dfu-tool:
  ubuntu: [rs-dfu-tool]
realsense-uvcvideo:
  ubuntu: [realsense-uvcvideo]
EOF

cat >/etc/ros/rosdep/sources.list.d/00-realsense.list <<'EOF'
yaml file:///srv/realsense.yaml
EOF
